app/cam/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import Required,Email,URL,EqualTo,Length
from wtforms import StringField,SubmitField,PasswordField,validators,SelectField, ValidationError,BooleanField,RadioField
from ..models import SVSIpCamReg


opt =  ["11*23","22*59","70*80","1080*1920"]
class CamRegister(Form):

    sitename = StringField('Your SiteName:-',validators = [Required(),Length(min=1,max=56)])
    camurl = StringField('Your Ip Cam URL:-',validators = [Required(),URL()])
    sitevis = SelectField("Select Your Visual Size", validators =[Required()],choices=[(f,f) for f in opt])
    FDStore = RadioField('Lable',choices=[('1','Yes Enable Face Detection'),('0','Not Enable Face Detection')])
    Camsubmit = SubmitField('Register')

class Camedit(Form):
    sitename = StringField('Your SiteName:-',validators = [Required(),Length(min=1,max=56)])
    camurl = StringField('Your Ip Cam URL:-',validators = [Required(),URL()])
    sitevis = SelectField("Select Your Visual Size", validators =[Required()],choices=[(f,f) for f in opt])
    FDStore = RadioField('Lable',choices=[('1','Yes Enable Face Detection'),('0','Not Enable Face Detection')])
    Camsubmit = SubmitField('Update Cam')

def validate_ipcam(self, field):
    if SVSIpCamReg.query.filter_by(camurl_hash=field.data).first():
        raise ValidationError('Cam URL is already register with us')

app/cam/__init__.py
from flask import Blueprint

cam = Blueprint('cam',__name__)

from . import  views

app/cam/views.py
from . import cam
from flask import render_template, redirect, request, url_for, flash,Response,session
from flask.ext.login import login_user, logout_user, login_required,current_user
from ..models import SVSIpCamReg,SVSuserReg
from .forms import CamRegister,Camedit
from ..email import send_email
from .. import db,login_manager
from datetime import datetime
#from camera import VideoCamera
from cryptography.fernet import Fernet


@cam.route('/Camregister', methods=['GET', 'POST'])
@login_required
def Camregister():
    form = CamRegister()
    if form.validate_on_submit():
        fkey = Fernet.generate_key()
        f = Fernet(fkey)
        ecamurl = f.encrypt(bytes(form.camurl.data))
        emid = SVSuserReg.query.filter_by(emid=current_user.emid).first()
        CamRef = SVSIpCamReg(camusername=emid,sitename =form.sitename.data,camurl_hash =ecamurl,key=fkey,sview=form.sitevis.data,FDstore = form.FDStore.data)
        db.session.add(CamRef)
        flash('Your cam has been added now.')
        return redirect(url_for('main.index'))
    return render_template('cam/IpCamReg.html', form=form)


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

#This link will stream from camera and convert it into jpeg and stream it

@cam.route('/stream')
@login_required
def stream():
    return Response(gen(VideoCamera()),mimetype='multipart/x-mixed-replace; boundary=frame')

#This link will show html which has img tag and source of it will be stream
@cam.route('/live')
@login_required
def live():
    return render_template('cam/stream.html')



#This route will show your camera list for loged in user
@cam.route('/listallcams')
@login_required
def listallcams():
   camtab = SVSIpCamReg.query.filter_by(u_id = current_user.id).all()
   for rec in camtab:
      dkey = rec.key
      bdkey=bytes(dkey)
      f = Fernet(bdkey)
      bcamurl = bytes(rec.camurl_hash)
      camurl =f.decrypt(bcamurl)
      rec.camurlnew = camurl

   return render_template('cam/viewallcam.html',allcam = camtab)

#This route will edit your camera url site and size in your
@cam.route('/editcams/<int:id>',methods=['GET','POST'])
def editcams(id):
    camedit = SVSIpCamReg.query.get_or_404(id)
    form = Camedit()
    if form.validate_on_submit():
        camedit.sitename = form.sitename.data
        fkey = Fernet.generate_key()
        f = Fernet(fkey)
        ecamurl = f.encrypt(bytes(form.camurl.data))
        camedit.key = fkey
        camedit.camurl_hash = ecamurl
        camedit.sview = form.sitevis.data
        camedit.FDstore = form.FDStore.data
        db.session.add(camedit)
        flash("Your Camera has been updated")
        return redirect(url_for('.listallcams'))
    form.sitename.data = camedit.sitename
    dkey = camedit.key
    bdkey=bytes(dkey)
    f = Fernet(bdkey)
    bcamurl = bytes(camedit.camurl_hash)
    camurl =f.decrypt(bcamurl)
    form.camurl.data = camurl
    form.sitevis.data = camedit.sview
    form.FDStore.data = str(camedit.FDstore)
    return render_template('cam/editcam.html',form=form)

app/templates/cam/IpCamReg.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}
SVS User IP camera Registration
{% endblock %}
{%block page_content%}
<div class="col-md-4">
{{ wtf.quick_form(form) }}
    </div>
{%endblock%}

app/templates/cam/camprofile.html
{% extends "base.html" %}
{% block title %}
SVS User IP camera List
{% endblock %}
{%block page_content%}
<ul>
    Your Registered Cam Lists are here:


</ul>
{%endblock%}

app/templates/cam/editcam.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}SVS - Cam Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Camera Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/cam/stream.html
{% extends "base.html" %}
{% block title %}
SVS Streaming Result.
{% endblock %}
{%block page_content%}
<article>

                       <h1>Your Live Streaming is done...</h1>

                        <img  id="bg" src="{{ url_for('cam.stream') }}">
</article>
{%endblock%}

app/templates/cam/viewallcam.html
{% extends "base.html" %}
{% block title %}
SVS List of all register camera
{% endblock %}
{%block page_content%}
<ul class="lead"><h3>Your Registered Cams List are here:</h3>
{% for cam in allcam %}
<li class="lead">


    <b>Location of Camera Site:</b>
<a href="http://maps.google.com/?q={{ cam.sitename}}">{{ cam.sitename }}</a>
<br>


            <b>Camera Viewing Window Size:</b>{{ cam.sview }}<br>
            <b>When Cam was added:</b>{{ moment(cam.camregdate).fromNow() }}<br>
            <b>Added By:</b><a href="{{ url_for('main.user', emid=cam.camusername.emid) }}">  {{ cam.camusername.fname }}</a><br>

            {% if cam.FDstore == 1 %}
            <b>Camera Face Detection Stored:</b>Enabled<br>
             <b>Start Cap</b><a href="{{ url_for('FD.FDStart') }}"> StartCap</a><br>

            {% else %}
            <b>Camera Face Detection Stored:</b>Disabled<br>
            {% endif %}
            <b>Camera URL:-</b>{{ cam.camurlnew }}<br>
            <img src="{{ cam.camurlnew }}">


            <a class="btn btn-default" href="{{ url_for('.editcams', id = cam.id) }}">Edit Camera</a>


    </li>
{% endfor %}
</ul>
{%endblock%}